export default {
  APP_NAME: 'Chinese Pod',
  FORGOT_MESSAGE:
    'Please enter your registered email Id, we will send you a reset link.',
  EMPTY_EMAIL: 'Email is Required',
  VALID_EMAIL: 'Please enter a valid email address',
  EMAIL_NOTREGD: 'Email you are using is not registered',
  LINK_SENT: 'Reset Link has been sent to your email address',
  EMPTY_NAME: 'Name is Required',
  EMPTY_PASS: 'Password is Required',
  EMPTY_ADDRESS_LINE1: 'Address line1 is Required',
  EMPTY_COUNTRY: 'Country is Required',
  EMPTY_STATE: 'State is Required',
  EMPTY_CITY: 'City is Required',
  EMPTY_PINCODE: 'Pincode is Required',
  VALID_PINCODE: 'Please enter a valid Pincode',
  EMPTY_CONFIRMPASS: 'Confirm Password is Required',
  DIFF_PASS: 'Password & Confirm Password must be same',
  API_BASE_URL: 'http://18.217.138.86/api/',
  ACCESSTOKEN_NAME: 'name of the token',
  USER_CREATED_AT: 'user created at',
  ARRAY_FAVORITE: 'name of the favourite array',
  EMAIL_NOTIFICATIONS: 'email notifications name',
  PUSH_NOTIFICATIONS: 'push notifications name',
  VALID_CARD_NUMBER: 'Please enter a valid Card Number',
  EMPTY_CARD_NUMBER: 'Card Number is Required',
  EMPTY_CVV: 'Cvv is Required',
  EMPTY_EXPIRY_MONTH: 'Expiry Month is Required',
  EMPTY_EXPIRY_YEAR: 'Expiry Year is Required',
  VALID_EXPIRY: 'Please enter a valid Expiry',
  VALID_CVV: 'Please enter a valid cvv',
  EMPTY_PROMOCODE: 'Promocode is Required',
};
